name: weather_app
description: A weather application using OpenWeather API.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^0.13.5
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  intl: ^0.18.0
  geolocator: ^10.1.0  # Add this for location services
  geocoding: ^2.1.1    # Add this for converting coordinates to city names

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  
